#!/usr/bin/env php
<?php

require_once __DIR__.'/autoload.php';

use SfPot\Command\ShowCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new ShowCommand());
$application->run();
